name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD: ${{ github.sha }}
      REPO: ${{ github.repository }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          git init .
          git config protocol.version 2
          git config http.https://github.com/.extraHeader \
            "AUTHORIZATION: basic $(printf "x-access-token:%s" "$GITHUB_TOKEN" | base64 -w 0)"
          git fetch --no-tags --prune --depth=1 "https://github.com/$REPO" "$HEAD"
          git checkout --force --detach FETCH_HEAD
      - run: |
          make R="$REPO" U="$GITHUB_ACTOR" P="$GITHUB_TOKEN"
